---
title: "Publications"
editor: visual
---

::: callout-note
## Links

> - **Duke Law**: <https://law.duke.edu/fac/qiao>
> - **Google Scholar**:<https://scholar.google.com/citations?user=SeUxOg4AAAAJ&hl=en>
> - **SSRN**:<https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=1485289>
:::

 

### **Forthcoming**

- [Governing With Digital Platforms: A Chinese Lesson for the U.S.?](https://ssrn.com/abstract=6110671), *Duke Journal of Comparative & International Law* ,forthcoming.

<!-- -->

- [Social Norms 2.0: From Private Governance to Co-evolution](https://ssrn.com/abstract=6408118) ,*Law and Social Inquiry*,*forthcoming. (invited book review)*

### **Books**

- [*The Authoritarian Commons: Neighborhood Democratization in Urban China*](https://worldcat.org/oclc/1454729785) (Cambridge University Press, 2025)

- [*Chinese Small Property: The Co-Evolution of Law and Social Norms*](http://www.worldcat.org/oclc/986788642) (Cambridge University Press, 2017)

### **Articles & Essays**

- [[*Local Resistance to Central Ideology: How Have Chinese Homeowners Contested the Party’s Leadership*]{.underline}](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5869582)*?*, 36 *Yale Journal of Law & the Humanities* 695–713 (2026).

- [From Taxi to Didi: Voice and Balancing in the Industrial Transition](https://doi.org/10.1017/lsi.2025.10092), *Law & Social Inquiry* (2025) (with Bingwan Xiong)

- [Communities Built on Political Trust: Theory and Evidence From China](https://doi.org/10.1177/00420980241252043), *Urban Studies* (2024) (with Yu Zeng)

- [Cooperating to Resist: Society and State During China’s COVID Lockdowns](https://ssrn.com/abstract=4575093), 35 *Yale Journal of Law & the Humanities* 877-924 (2024)

  - Featured in [[HealthLawProf Blog]{.underline}](https://lawprofessors.typepad.com/healthlawprof_blog/2023/11/cooperating-to-resist-society-and-state-during-chinas-covid-lockdowns.html).

- [Workload, Legal Doctrine, and Judicial Review in an Authoritarian Regime: A Study of Expropriation Judgments in China](https://doi.org/10.1016/j.irle.2024.106232), 80 *International Review of Law and Economics*, article 106232, 1-15 (2024) (with Chaoqun Zhan)

  - Featured in [[National Affairs website]{.underline}](https://www.nationalaffairs.com/blog/detail/findings-a-daily-roundup/global-governance).

- [Finance Against Law: The Case of China](https://scholarship.law.duke.edu/faculty_scholarship/4509), 64 *Harvard International Law Journal* 431-487 (2023)

  - Invited blog posts: [[Columbia Law School Blue Sky Blog]{.underline}](https://clsbluesky.law.columbia.edu/2022/09/20/finance-without-law-the-case-of-china/); [[The FinReg Blog]{.underline}](https://sites.duke.edu/thefinregblog/2022/09/29/finance-without-law-the-case-of-china/) (Duke Financial Economics Center)

  - [[Talk at NYU US-Asia Law Institute]{.underline}](https://www.youtube.com/watch?v=_4-z4rKMDVw)

  - [Cited in the [2023 Report to Congress of The U.S.-China Economic and Security Review Commission]{.underline}](https://www.uscc.gov/sites/default/files/2023-11/2023_Annual_Report_to_Congress.pdf)

- [The Authoritarian Commons: Divergent Paths of Neighborhood Democratization in Three Chinese Megacities](https://doi.org/10.1093/ajcl/avad023), 71 *American Journal of Comparative Law* 388-443 (2023)

  - Hessel Yntema Prize, American Society of Comparative Law, 2024.

- [Land Options for Housing: How New Property Rights Can Break Old Land Monopolies](https://scholarship.law.duke.edu/faculty_scholarship/4512), 44 *University of Pennsylvania Journal of International Law* 163-233 (2022) (with Roderick M. Hills, Jr.)

  - Invited op-eds: [[South China Morning Post]{.underline}](https://www.scmp.com/author/qiao-shitong)

  - Featured in [[China Daily]{.underline}](https://www.chinadailyhk.com/article/249172?showpdf=true); [[Phoenix Weekly (凤凰周刊)]{.underline}](http://www.ifengweekly.com/detil.php?id=20401)

  - [[Talk at HKU Faculty of Law]{.underline}](https://www.youtube.com/watch?v=DEjwNJqDG78)

- [The Structure and Spirit of Chinese Property Law](https://doi.org/10.4324/9781003139614), in *The Routledge Handbook of Property, Law and Society* 52-60 (Nicole Graham, Margaret Davies, and Lee Godden eds., 2022)

- [Legal Doctrine and Judicial Review of Eminent Domain in China](https://doi.org/10.1017/lsi.2020.41), 46 *Law and Social Inquiry* 826-859 (2021) (with Wenzheng Mao)

- [Expropriation in the Name of Rights: Transferable Development Rights (TDRs), the Bundle of Sticks and Chinese Politics](https://scholarship.law.duke.edu/faculty_scholarship/4078), 13 *New York University Journal of Law & Liberty* 1-43 (2019)

- [Fragmented Laws, Contingent Choices: The Tragicomedy of the Village Commons in China](https://scholarship.law.duke.edu/djcil/vol29/iss2/3/), 29 *Duke Journal of Comparative & International Law* 235-275 (2019)

  - Selected as one of the eleven papers presented at the *2015 International Junior Faculty Forum* (Stanford Law School)

  - Honorable Mention of the 2019 Asian Law and Society Association Distinguished Article Award

- [Binding Leviathan: Credible Commitment in an Authoritarian Regime](https://scholarship.law.duke.edu/faculty_scholarship/4510), 102 *Minnesota Law Review* 1591-1617 (2018) (with Roderick M. Hills, Jr.)

- [Exclusionary Megacities](https://scholarship.law.duke.edu/faculty_scholarship/4081), 91 *Southern California Law Review* 467-522 (2018) (with Wendell Pritchett)

  - Reported by *Caixin* (a leading Chinese news media);

- [Foreword: Introduction to Decentralization and Development](https://scholarship.law.duke.edu/faculty_scholarship/4513), 102 *Minnesota Law Review* 1485-1492 (2018) (with Richard Epstein)

- [Rights-Weakening Federalism](https://scholarship.law.duke.edu/faculty_scholarship/4083), 102 *Minnesota Law Review* 1671-1702 (2018)

- [China's Changing Property Law Landscape](https://doi.org/10.4337/9781785369162.00023), in [*Comparative Property Law: Global Perspectives*](https://worldcat.org/oclc/972729862) 311-332 (Michele Graziadei & Lionel Smith eds., 2017) (with Frank K. Upham)

- [The Evolution of Chinese Property Law: Stick by Stick?](https://doi.org/10.1017/9781316658925.008), in [*Private Law in China and Taiwan: Legal and Economic Analyses*](https://worldcat.org/oclc/951465405) 182-211 (Yun-chien Chang, Wei Shen & Wen-yeu Wang eds., 2017) (with Frank K. Upham)

  - Reviewed in Gregory M. Stein, [[*The Sticks in the Chinese Property Rights Bundle*]{.underline}](https://property.jotwell.com/the-sticks-in-the-chinese-property-rights-bundle/), [JOTWELL]{.smallcaps} (The Journal of Things We Like (Lots)) (June 15, 2017)

- [Voice and Exit as Accountability Mechanisms: Can Foot-Voting Be Made Safe for the Chinese Communist Party?](https://scholarship.law.duke.edu/faculty_scholarship/4082), 48 *Columbia Human Rights Law Review* 158-210 (2017) (with Roderick M. Hills, Jr.)

  - Featured in [[Legal Theory Blog]{.underline}](https://lsolum.typepad.com/legaltheory/2016/08/hills-qiao-on-foot-voting-the-prc.html)

- [Dealing With Illegal Housing: What Can New York City Learn From Shenzhen](https://scholarship.law.duke.edu/faculty_scholarship/4076), 43 *Fordham Urban Law Journal* 713-740 (2016)

  - Chinese translation: Huina Xiao trans. [Weifa fangwu yu fanxiang quhua: jiyu niuyue he Shenzhen de bijiao yanjiu]{.smallcaps}, [Chengshi Zhili Yanjiu]{.smallcaps} \[[Urban Governance Studies]{.smallcaps}\], Vol. 1, 15-39, 2017.

- [Small Property, Adverse Possession and Optional Law](https://doi.org/10.1017/CBO9781316017814.012), in [*Law and Economics of Possession*](https://search.worldcat.org/title/892620585) 290-319 (Yun-chien Chang ed., 2015)

  - HKU Faculty of Law Research Award

  - Chinese translation: Yulan Liu trans. [Xiaochanquan Da Shichang: Jiaodian yu Boyi, BI Jiao \[Comparative Studies\], Vol. 5, 2019.]{.smallcaps}

- [Small Property, Big Market: A Focal Point Explanation](https://doi.org/10.5131/AJCL.2015.0006), 63 *American Journal of Comparative Law* 197-238 (2015)

- [The Evolution of Relational Property Rights: A Case of Chinese Rural Land Reform](https://scholarship.law.duke.edu/faculty_scholarship/4080), 100 *Iowa Law Review* 2479-2506 (2015) (with Frank K. Upham)

  - Featured at *Oxford Business Law Blog* 

  - Chinese translation published at [Shi Da Fa Xue]{.smallcaps} \[[ECNU Law Review\], Vol. 3, 2018.]{.smallcaps} 

- [The Politics of Chinese Land: Partial Reform, Vested Interests and Small Property](https://scholarship.law.duke.edu/faculty_scholarship/4079), 29 *Columbia Journal of Asian Law* 70-112 (2015)

- [Planting Houses in Shenzhen: A Real Estate Market Without Legal Titles](https://doi.org/10.1017/cls.2013.58), 29 *Canadian Journal of Law and Society* 253-272 (2014)

- [Governing the Post-Socialist Transitional Commons: A Case from Rural China](https://scholarship.law.duke.edu/faculty_scholarship/4514), 24 *Colorado Journal of International Environmental Law and Policy* 117-162 (2013), reprinted in 1 *Brigham-Kanner Property Rights Conference Journal* 303-344 (2012)

- [Whither China’s Non-Interference Principle?](https://ssrn.com/abstract=1967551), 4 *European Society of International Law (ESIL) Research Forum* 1-25 (2011)

- 权利分置的逻辑\[*The Logic of Rights Separation*\], 法律与社会科学\[Law and Social Sciences\], 2023.

- 行政征收的司法控制之道：基于各高级法院裁判文书的分析\[*Strategic Adjudication: Eminent Domain in High People’s Courts*\]，清华法学[\[Tsinghua University Law Journal\]]{.smallcaps}, Vol. 4, 2018（与毛文峥合著）

  - Cited in Jiang Bixin (江必新, Vice President of the Supreme People’s Court and Grand Justice of the Second Rank), Several Relationships in the Revision of the Land Administration Law (修改《土地管理法》應當處理好的幾對關系), [Journal of Law Application (法律適用)]{.smallcaps}, No.7, p. 4 (2019).

### **Newspaper Articles and Commentary**

- [Cleanup of China Evergrande Collapse Calls for Coordination and Clarity](https://asia.nikkei.com/Opinion/Cleanup-of-China-Evergrande-collapse-calls-for-coordination-and-clarity), *Nikkei Asia* (March 6, 2024)

- [How Technology Is Changing Justice in China](https://judicature.duke.edu/articles/technology-changing-justice-in-china/), *Judicature International* (June 1, 2022) (with others)

- [A Rural-Urban Crossroads in Chinese Law: Qiao Shitong on the Development and Future of Chinese Eminent Domain](https://www.scmp.com/business/article/3168623/breaking-old-land-monopoly-hong-kong-resolve-citys-housing-crisis), *Bulletin -- Columbia Journal of Transnational Law* (March 3, 2022) (with Marc Chien)

- Breaking Old Land Monopoly in Hong Kong to Resolve the City’s Housing Crisis, *South China Morning Post* (March 1, 2022) (with Roderick M. Hills, Jr.)

- [Development Rights for All](https://usali.org/usali-perspectives-blog/development-rights-for-all), 1 *USALI Perspectives* (June 17, 2021) (with Roderick M. Hills, Jr.)

- [Here Is How TDRs Outweigh Lantau Reclamation Plan](https://www.scmp.com/business/article/3127619/heres-how-transferable-development-rights-outweigh-lantau-reclamation-plan), *South China Morning Post* (March 31, 2021, at p2) (with Roderick M. Hills, Jr.)

- [A New Age for the WHO?](https://usali.org/usali-perspectives-blog/a-new-age-for-the-who ), USALI Perspectives (January 4, 2021).

- [Killing Two Birds with One Stone: How to End Rural Land Expropriation and Secure Tenure for Urban Property Owners at the Same Time](https://usali.org/usali-perspectives-blog/tag/Roderick+Hills+Jr), USALI Perspectives (January 21, 2021) (with Roderick M. Hills, Jr.).
  

### **Media Interviews and Opinions** 
Agence France-Presse; BBC; China Daily; Deutsche Welle; Frankfurter Allgemeine Zeitung (FAZ); The Guardian; South China Morning Post; The Global and Mail; Oxford Business Law Blog; Bloomberg; NPR; New York Times; The Washington Post; People’s Court Daily (人民法院报); Caixin (财新); China Reform (中国改革); Phoenix Weekly (凤凰周刊)